### ISSUE TITLE
[ERROR] lua/autorun/client/cl_viralsscoreboard.lua:264

### ISSUE THREAD

**Issue by jmne** [viral32111/virals-scoreboard#1]
[ERROR] lua/autorun/client/cl_viralsscoreboard.lua:264: attempt to call method 'hide' (a nil value)
  1. fn - lua/autorun/client/cl_viralsscoreboard.lua:264
   2. Call - addons/ulib/lua/ulib/shared/hook.lua:109
    3. func - addons/scoreboard_ranks/lua/autorun/client/cl_tttsbranks.lua:12
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by viral32111** [comment]
From what i can tell there is an addon overriding my scoreboard called `scoreboard_ranks`, If this creates ranks on the scoreboard then it is not needed, My scoreboard has its own ranking system.
